### ISSUE TITLE
Implicit operator doesn't work with null

### ISSUE THREAD

**Issue by jstafford5380** [ymassad/MaybeExamples#1]
https://github.com/ymassad/MaybeExamples/blob/36e02423f0162ec52a64456b4537962658633f77/MaybeAsASumType/Maybe.cs#L43-L49

Does this even bring any value? Implicitly converting `null` to `Maybe<T>`  doesn't wrap it, it just gives you `null`. Am I missing something?

```csharp
Maybe<int> x = null;
x.Match(...); // throws null reference exception

Maybe<int> y = (Maybe<int>) null;
y.Match(...); // still throws null reference exception

Maybe<int> z = null as Maybe<int>;
z.Match(...); // still throws null reference exception
```

**Comment by jstafford5380** [comment]
Oh looks like someone else ran across the same issude XD https://stackoverflow.com/questions/52393418/implicit-conversion-from-null. So in other words, no, that operator has no value and we need to use `Maybe<T>.None` which is a bit of a bummer because that means you still have to put traditional mapping logic in your code at some point  (i.e. `if(x == null) { x1 = Maybe<int>.None; }` :(

**Comment by jstafford5380** [comment]
Ah ok. So you can't do it with an explicit null, only a null instance of an object. Fair. 

```csharp
string foo = null;
Maybe<string> x = foo;
x.Match(...); // works
```

**Comment by ymassad** [comment]
I use the Maybe<T> type that is a struct. The one here:

https://github.com/ymassad/MaybeExamples/blob/master/MaybeAsAStruct/Maybe.cs

Because it is a struct, we are guaranteed by the runtime that it will never be null.

With this one, you can do:

```csharp
Maybe<string> x = default;
```

Assuming you have C# 7.1 or later.
